name: Autorerun

on:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: rerun-${{ github.event.workflow_run.id }}

jobs:
  rerun:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/autorerun@v0.35.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
