
name: OpenTelemetry
on:
  workflow_run:
    workflows:
      - Accept Invitations
      - Approve
      - Autoapprove
      - Autoassign
      - Autorerun
      - Autoversion
      - Copilot coding agent
      - Onboard
      - Renovate
      - Rotate Tokens
    types:
      - completed
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/workflow@v5.38.2
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
    permissions:
      actions: read
